"""Fountain screenplay data models and formatter."""

from __future__ import annotations
from enum import Enum
from typing import List, Dict, Any, Optional
import uuid
from pydantic import BaseModel, ConfigDict, Field


class ScreenplayBlockType(str, Enum):
    """Fountain screenplay element types."""
    SCENE_HEADING = "scene_heading"
    ACTION = "action"
    CHARACTER = "character"
    PARENTHETICAL = "parenthetical"
    DIALOGUE = "dialogue"
    TRANSITION = "transition"


class ScreenplayBlock(BaseModel):
    """An individual element of a screenplay linked to underlying simulation events."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str = Field(default_factory=lambda: f"blk_{uuid.uuid4().hex[:8]}")
    block_type: ScreenplayBlockType
    text: str
    source_event_ids: List[str] = Field(default_factory=list)
    character_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ScreenplayScene(BaseModel):
    """A scene containing ordered screenplay blocks."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    scene_number: int = Field(ge=1)
    location_id: str
    heading: str
    blocks: List[ScreenplayBlock] = Field(default_factory=list)
    source_event_ids: List[str] = Field(default_factory=list)


class ScreenplayDocument(BaseModel):
    """Complete Fountain-compatible screenplay with event provenance."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    title: str = "UNTITLED SIMULATION"
    credit: str = "Generated by"
    author: str = "D3 Story Lab"
    draft_date: str = "2026"
    scenes: List[ScreenplayScene] = Field(default_factory=list)

    def to_fountain(self) -> str:
        """Render the screenplay document into canonical Fountain text format."""
        lines: List[str] = []

        # Title Page
        lines.append(f"Title: {self.title}")
        lines.append(f"Credit: {self.credit}")
        lines.append(f"Author: {self.author}")
        lines.append(f"Draft date: {self.draft_date}\n\n")

        for scene in self.scenes:
            # Scene Heading (e.g. INT. HOTEL PENTHOUSE - NIGHT)
            lines.append(scene.heading.upper())
            lines.append("")

            for block in scene.blocks:
                if block.block_type == ScreenplayBlockType.SCENE_HEADING:
                    # Already handled or inline sub-slug
                    lines.append(block.text.upper())
                    lines.append("")
                elif block.block_type == ScreenplayBlockType.ACTION:
                    lines.append(block.text)
                    lines.append("")
                elif block.block_type == ScreenplayBlockType.CHARACTER:
                    lines.append(block.text.upper())
                elif block.block_type == ScreenplayBlockType.PARENTHETICAL:
                    lines.append(f"({block.text.strip('()')})")
                elif block.block_type == ScreenplayBlockType.DIALOGUE:
                    lines.append(block.text)
                    lines.append("")
                elif block.block_type == ScreenplayBlockType.TRANSITION:
                    lines.append(f"{block.text.upper()}:")
                    lines.append("")

        return "\n".join(lines).strip() + "\n"

    def get_provenance_map(self) -> Dict[str, List[str]]:
        """Map each block ID to its underlying simulation event IDs."""
        prov: Dict[str, List[str]] = {}
        for scene in self.scenes:
            for block in scene.blocks:
                prov[block.id] = block.source_event_ids
        return prov
