"""Storyboard Control Bundle and Previs Control Renderer.

Reclassifies and reuses the procedural SVG engine as an internal planning and guidance tool.
Produces structural control maps for generative models (ControlNet, IP-Adapter) and interactive previs inspection:
1. Pose Map (skeletal wireframes / pose guides)
2. Edge Map (high-contrast contour linework)
3. Depth Map (luminance depth approximation: foreground light, background dark)
4. Composition Mask (rule-of-thirds, diagonals, focal zones)
5. Camera Layout (camera angle, FOV, actor blocking)
"""

from __future__ import annotations
import html
import logging
from typing import Dict, Any, Optional, List
from pydantic import BaseModel, ConfigDict, Field

from src.storyboard.models import StoryboardPanel, ShotType, CameraAngle
from src.storyboard.visual_bible import VisualBible
from src.storyboard.asset_store import StoryboardAssetStore
from src.storyboard.sketch.staging import SceneStager, StagedScene
from src.storyboard.sketch.character import CharacterSketchRenderer
from src.storyboard.sketch.props import PropSketchRenderer
from src.storyboard.sketch.environment import EnvironmentSketchRenderer

logger = logging.getLogger(__name__)


class StoryboardControlBundle(BaseModel):
    """Structural guidance assets generated by the internal previs engine."""
    model_config = ConfigDict(extra="ignore")

    pose_map: Optional[str] = None
    edge_map: Optional[str] = None
    depth_map: Optional[str] = None
    composition_mask: Optional[str] = None
    camera_layout: Optional[str] = None
    previs_svg: Optional[str] = None
    camera_details: Dict[str, Any] = Field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(mode="json")


class PrevisControlRenderer:
    """Internal previs and control asset generator.

    NOTE: The output of this renderer is STRICTLY for:
    - Internal model conditioning (ControlNet / Guidance)
    - Previs / blocking inspection in developer/debug UI
    It is NOT final user-facing artwork.
    """

    def __init__(self, asset_store: Optional[StoryboardAssetStore] = None):
        self.asset_store = asset_store or StoryboardAssetStore()
        self.char_renderer = CharacterSketchRenderer()
        self.prop_renderer = PropSketchRenderer()
        self.env_renderer = EnvironmentSketchRenderer()

    def generate_control_bundle(
        self,
        panel: StoryboardPanel,
        bible: Optional[VisualBible] = None,
        version: int = 1,
    ) -> StoryboardControlBundle:
        """Synthesize all control maps (pose, edge, depth, composition, camera layout)."""
        w, h = 960.0, 540.0
        seed_base = f"{panel.project_id}_{panel.panel_id or panel.id}"
        staged: StagedScene = SceneStager.stage_panel(panel, version=version, seed=seed_base)
        project_id = panel.project_id or "default"
        pid = panel.panel_id or panel.id

        # 1. Pose Map (Skeleton wireframes on neutral dark backdrop)
        pose_svg = self._render_pose_map(staged, w, h)
        pose_url = self._save_control_asset(project_id, f"{pid}_pose_v{version}.svg", pose_svg)

        # 2. Edge Map (Clean vector edge contours without fills or textures)
        edge_svg = self._render_edge_map(staged, w, h)
        edge_url = self._save_control_asset(project_id, f"{pid}_edge_v{version}.svg", edge_svg)

        # 3. Depth Map (Luminance depth approximation: close=light, far=dark)
        depth_svg = self._render_depth_map(staged, w, h)
        depth_url = self._save_control_asset(project_id, f"{pid}_depth_v{version}.svg", depth_svg)

        # 4. Composition Mask (Rule of thirds, perspective diagonals, golden ratio, safe zones)
        comp_svg = self._render_composition_mask(staged, w, h, panel)
        comp_url = self._save_control_asset(project_id, f"{pid}_comp_v{version}.svg", comp_svg)

        # 5. Camera Layout (Blocking schematic showing camera FOV cone & actor positions)
        layout_svg = self._render_camera_layout(staged, w, h, panel)
        layout_url = self._save_control_asset(project_id, f"{pid}_layout_v{version}.svg", layout_svg)

        # 6. Combined Previs Guide (Full previs layout for inspector view)
        previs_svg = self._render_previs_guide(staged, w, h, panel)
        previs_url = self._save_control_asset(project_id, f"{pid}_previs_v{version}.svg", previs_svg)

        camera_details = {
            "shot_type": panel.shot_type.value,
            "camera_angle": panel.camera_angle.value,
            "lens_feel": panel.lens_feel,
            "dutch_angle_deg": staged.dutch_rotation_deg,
            "focal_depth_plane": panel.focal_depth_plane,
            "actors_staged": [getattr(a, 'name', 'Actor') for a in staged.actors],
            "props_staged": [p.name for p in staged.props],
            "previs_url": previs_url,
        }

        return StoryboardControlBundle(
            pose_map=pose_url,
            edge_map=edge_url,
            depth_map=depth_url,
            composition_mask=comp_url,
            camera_layout=layout_url,
            previs_svg=previs_svg,
            camera_details=camera_details,
        )

    def _save_control_asset(self, project_id: str, filename: str, content: str) -> str:
        try:
            return self.asset_store.save_asset(
                project_id=project_id,
                category="controls",
                filename=filename,
                content=content,
            )
        except Exception as e:
            logger.warning(f"Failed to persist control asset {filename}: {e}")
            return f"/api/projects/{project_id}/storyboard/assets/controls/{filename}"

    def _render_pose_map(self, staged: StagedScene, w: float, h: float) -> str:
        """Render skeletal pose lines representing OpenPose-like structural joints."""
        elements = [f'<rect width="{w}" height="{h}" fill="#0a0a0c"/>']
        elements.append('<!-- OpenPose / Skeleton Structural Guidance -->')
        for actor in staged.actors:
            cx = float(actor.x)
            top_y = float(actor.y)
            actor_h = float(actor.height)
            cy = top_y + (actor_h * 0.5)
            scale = max(actor_h / 280.0, 0.25)
            # Head circle
            head_y = top_y + (22.0 * scale)
            elements.append(f'<circle cx="{cx:.1f}" cy="{head_y:.1f}" r="{18.0 * scale:.1f}" fill="none" stroke="#00ffcc" stroke-width="4"/>')
            # Spine
            neck_y = head_y + 18.0 * scale
            pelvis_y = cy + 20.0 * scale
            elements.append(f'<line x1="{cx:.1f}" y1="{neck_y:.1f}" x2="{cx:.1f}" y2="{pelvis_y:.1f}" stroke="#0088ff" stroke-width="5"/>')
            # Shoulders
            shoulder_w = 40.0 * scale
            l_sh_x, r_sh_x = cx - shoulder_w, cx + shoulder_w
            sh_y = neck_y + 10.0 * scale
            elements.append(f'<line x1="{l_sh_x:.1f}" y1="{sh_y:.1f}" x2="{r_sh_x:.1f}" y2="{sh_y:.1f}" stroke="#ff0055" stroke-width="4"/>')
            # Arms
            elements.append(f'<line x1="{l_sh_x:.1f}" y1="{sh_y:.1f}" x2="{(l_sh_x - 15 * scale):.1f}" y2="{(cy + 10 * scale):.1f}" stroke="#ffaa00" stroke-width="3"/>')
            elements.append(f'<line x1="{r_sh_x:.1f}" y1="{sh_y:.1f}" x2="{(r_sh_x + 15 * scale):.1f}" y2="{(cy + 10 * scale):.1f}" stroke="#ffaa00" stroke-width="3"/>')
            # Legs
            elements.append(f'<line x1="{(cx - 15 * scale):.1f}" y1="{pelvis_y:.1f}" x2="{(cx - 20 * scale):.1f}" y2="{(cy + 75 * scale):.1f}" stroke="#00ff44" stroke-width="4"/>')
            elements.append(f'<line x1="{(cx + 15 * scale):.1f}" y1="{pelvis_y:.1f}" x2="{(cx + 20 * scale):.1f}" y2="{(cy + 75 * scale):.1f}" stroke="#00ff44" stroke-width="4"/>')

        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">'
            + "\n".join(elements)
            + "</svg>"
        )

    def _render_edge_map(self, staged: StagedScene, w: float, h: float) -> str:
        """Render high-contrast wireframe edge map (Canny / line art approximation)."""
        elements = [f'<rect width="{w}" height="{h}" fill="#000000"/>']
        elements.append('<!-- Edge Map / Canny Linework Approximation -->')
        # Room boundaries
        elements.append(f'<line x1="0" y1="{h * 0.7:.1f}" x2="{w}" y2="{h * 0.7:.1f}" stroke="#ffffff" stroke-width="2"/>')
        elements.append(f'<line x1="{w * 0.2:.1f}" y1="0" x2="{w * 0.2:.1f}" y2="{h * 0.7:.1f}" stroke="#888888" stroke-width="1.5"/>')
        elements.append(f'<line x1="{w * 0.8:.1f}" y1="0" x2="{w * 0.8:.1f}" y2="{h * 0.7:.1f}" stroke="#888888" stroke-width="1.5"/>')
        # Actor contour silhouettes
        for actor in staged.actors:
            cx = float(actor.x)
            top_y = float(actor.y)
            actor_h = float(actor.height)
            actor_w = max(actor_h * 0.35, 30.0)
            left_x = cx - (actor_w * 0.5)
            elements.append(
                f'<rect x="{left_x:.1f}" y="{top_y:.1f}" width="{actor_w:.1f}" height="{actor_h:.1f}" '
                f'rx="8" fill="none" stroke="#ffffff" stroke-width="3"/>'
            )
            head_r = actor_w * 0.32
            elements.append(f'<circle cx="{cx:.1f}" cy="{top_y + head_r * 1.5:.1f}" r="{head_r:.1f}" fill="none" stroke="#ffffff" stroke-width="2.5"/>')
        # Props
        for prop in staged.props:
            pscale = getattr(prop, 'scale', 1.0)
            pw, ph = 40.0 * pscale, 40.0 * pscale
            px = float(prop.cx) - (pw * 0.5)
            py = float(prop.cy) - (ph * 0.5)
            elements.append(f'<rect x="{px:.1f}" y="{py:.1f}" width="{pw:.1f}" height="{ph:.1f}" fill="none" stroke="#ffff00" stroke-width="2"/>')

        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">'
            + "\n".join(elements)
            + "</svg>"
        )

    def _render_depth_map(self, staged: StagedScene, w: float, h: float) -> str:
        """Render depth map luminance (white = close to lens, black = distant background)."""
        elements = [f'<rect width="{w}" height="{h}" fill="#111115"/>']
        elements.append('<!-- Depth Map (Luminance Depth Approximation) -->')
        # Background elements (depth = 0.2, dark gray)
        elements.append(f'<rect x="0" y="{h * 0.35:.1f}" width="{w}" height="{h * 0.35:.1f}" fill="#33333b"/>')
        # Midground floor plane (depth gradient)
        elements.append(f'<polygon points="0,{h} {w},{h} {w * 0.85},{h * 0.6} {w * 0.15},{h * 0.6}" fill="#4a4a58"/>')
        # Actors: closer actors get brighter luminance
        for idx, actor in enumerate(staged.actors):
            cx = float(actor.x)
            top_y = float(actor.y)
            actor_h = float(actor.height)
            actor_w = max(actor_h * 0.35, 30.0)
            left_x = cx - (actor_w * 0.5)
            # Estimate closeness based on actor height relative to canvas height
            closeness = min(max(actor_h / h, 0.2), 0.95)
            lum_val = int(closeness * 255)
            hex_color = f"#{lum_val:02x}{lum_val:02x}{lum_val:02x}"
            elements.append(
                f'<rect x="{left_x:.1f}" y="{top_y:.1f}" width="{actor_w:.1f}" height="{actor_h:.1f}" '
                f'rx="12" fill="{hex_color}" stroke="#ffffff" stroke-width="1"/>'
            )
        # Foreground props
        for prop in staged.props:
            pscale = getattr(prop, 'scale', 1.0)
            pw, ph = 40.0 * pscale, 40.0 * pscale
            px = float(prop.cx) - (pw * 0.5)
            py = float(prop.cy) - (ph * 0.5)
            elements.append(f'<rect x="{px:.1f}" y="{py:.1f}" width="{pw:.1f}" height="{ph:.1f}" fill="#ffffff"/>')

        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">'
            + "\n".join(elements)
            + "</svg>"
        )


    def _render_composition_mask(self, staged: StagedScene, w: float, h: float, panel: StoryboardPanel) -> str:
        """Render composition guides (Rule of Thirds, diagonals, center safe frame, focal target)."""
        elements = [f'<rect width="{w}" height="{h}" fill="#0d1117" fill-opacity="0.85"/>']
        elements.append('<!-- Composition & Framing Guide Mask -->')
        # Rule of Thirds
        x1, x2 = w / 3.0, (w * 2.0) / 3.0
        y1, y2 = h / 3.0, (h * 2.0) / 3.0
        elements.append(f'<line x1="{x1}" y1="0" x2="{x1}" y2="{h}" stroke="#38bdf8" stroke-dasharray="6,6" stroke-width="1.5" opacity="0.6"/>')
        elements.append(f'<line x2="{x2}" y1="0" x1="{x2}" y2="{h}" stroke="#38bdf8" stroke-dasharray="6,6" stroke-width="1.5" opacity="0.6"/>')
        elements.append(f'<line x1="0" y1="{y1}" x2="{w}" y2="{y1}" stroke="#38bdf8" stroke-dasharray="6,6" stroke-width="1.5" opacity="0.6"/>')
        elements.append(f'<line x1="0" y1="{y2}" x2="{w}" y2="{y2}" stroke="#38bdf8" stroke-dasharray="6,6" stroke-width="1.5" opacity="0.6"/>')
        # Power intersection nodes
        for px in (x1, x2):
            for py in (y1, y2):
                elements.append(f'<circle cx="{px}" cy="{py}" r="6" fill="#f59e0b" opacity="0.8"/>')
        # Safe area border (90%)
        sw, sh = w * 0.9, h * 0.9
        sx, sy = (w - sw) / 2.0, (h - sh) / 2.0
        elements.append(f'<rect x="{sx:.1f}" y="{sy:.1f}" width="{sw:.1f}" height="{sh:.1f}" fill="none" stroke="#22c55e" stroke-width="1" stroke-dasharray="4,4" opacity="0.5"/>')
        # Center crosshair
        elements.append(f'<line x1="{w/2 - 15}" y1="{h/2}" x2="{w/2 + 15}" y2="{h/2}" stroke="#ef4444" stroke-width="2"/>')
        elements.append(f'<line x1="{w/2}" y1="{h/2 - 15}" x2="{w/2}" y2="{h/2 + 15}" stroke="#ef4444" stroke-width="2"/>')
        # Label
        elements.append(
            f'<text x="24" y="36" fill="#94a3b8" font-family="monospace" font-size="14" font-weight="bold">'
            f'COMPOSITION GUIDE • {panel.shot_type.value.upper()} • {panel.camera_angle.value.upper()}</text>'
        )

        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">'
            + "\n".join(elements)
            + "</svg>"
        )

    def _render_camera_layout(self, staged: StagedScene, w: float, h: float, panel: StoryboardPanel) -> str:
        """Render overhead blocking schematic showing camera position, FOV cone, and actor coordinates."""
        elements = [f'<rect width="{w}" height="{h}" fill="#0f172a"/>']
        elements.append('<!-- Camera & Blocking Layout Schematic -->')
        # Top-down room outline
        margin = 40.0
        elements.append(f'<rect x="{margin}" y="{margin}" width="{w - margin * 2}" height="{h - margin * 2}" fill="#1e293b" stroke="#334155" stroke-width="2"/>')
        # Camera placement at bottom center
        cam_x, cam_y = w / 2.0, h - margin - 20.0
        elements.append(f'<circle cx="{cam_x}" cy="{cam_y}" r="12" fill="#ef4444"/>')
        elements.append(f'<polygon points="{cam_x - 10},{cam_y - 12} {cam_x + 10},{cam_y - 12} {cam_x},{cam_y - 24}" fill="#ef4444"/>')
        # Camera FOV Cone
        elements.append(f'<line x1="{cam_x}" y1="{cam_y}" x2="{margin + 40}" y2="{margin + 40}" stroke="#ef4444" stroke-dasharray="4,4" opacity="0.4"/>')
        elements.append(f'<line x1="{cam_x}" y1="{cam_y}" x2="{w - margin - 40}" y2="{margin + 40}" stroke="#ef4444" stroke-dasharray="4,4" opacity="0.4"/>')
        # Actor blocking markers
        for idx, actor in enumerate(staged.actors):
            cx = float(actor.x)
            name = getattr(actor, 'name', 'Actor')
            ax = margin + (w - margin * 2) * max(min(cx / w, 0.95), 0.05)
            ay = margin + (h - margin * 2) * 0.45 + (idx * 30)
            elements.append(f'<circle cx="{ax:.1f}" cy="{ay:.1f}" r="14" fill="#3b82f6" stroke="#ffffff" stroke-width="2"/>')
            elements.append(f'<text x="{ax:.1f}" y="{ay + 5:.1f}" fill="#ffffff" font-family="sans-serif" font-size="11" text-anchor="middle" font-weight="bold">{html.escape(name[:1])}</text>')
            elements.append(f'<text x="{ax:.1f}" y="{ay + 25:.1f}" fill="#94a3b8" font-family="monospace" font-size="10" text-anchor="middle">{html.escape(name[:12])}</text>')
        # Legend
        elements.append(
            f'<text x="60" y="70" fill="#f8fafc" font-family="sans-serif" font-size="14" font-weight="bold">'
            f'CAMERA BLOCKING SCHEMATIC: {panel.lens_feel}</text>'
        )

        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">'
            + "\n".join(elements)
            + "</svg>"
        )

    def _render_previs_guide(self, staged: StagedScene, w: float, h: float, panel: StoryboardPanel) -> str:
        """Full internal previs guide drawing. NOT FOR FINAL ARTWORK PRESENTATION."""
        shot_type = panel.shot_type.value.replace("_", " ").upper()
        cam_angle = panel.camera_angle.value.replace("_", " ").upper()
        action_clean = html.escape(panel.action or panel.action_description or "Scene action")

        # Basic wireframe background
        svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(w)} {int(h)}" width="100%" height="100%">
  <!-- PREVIS CONTROL GUIDE ONLY - NOT FINAL ARTWORK -->
  <defs>
    <linearGradient id="previsBg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#18181b"/>
      <stop offset="100%" stop-color="#09090b"/>
    </linearGradient>
  </defs>
  <rect width="{w}" height="{h}" fill="url(#previsBg)"/>

  <!-- Grid Layout -->
  <line x1="0" y1="{h * 0.65:.1f}" x2="{w}" y2="{h * 0.65:.1f}" stroke="#3f3f46" stroke-width="2"/>
  <line x1="{w * 0.2:.1f}" y1="0" x2="{w * 0.2:.1f}" y2="{h * 0.65:.1f}" stroke="#27272a" stroke-width="1.5"/>
  <line x1="{w * 0.8:.1f}" y1="0" x2="{w * 0.8:.1f}" y2="{h * 0.65:.1f}" stroke="#27272a" stroke-width="1.5"/>

  <!-- Previs Banner Warning -->
  <rect x="0" y="0" width="{w}" height="32" fill="#27272a" opacity="0.95"/>
  <text x="16" y="21" fill="#e4e4e7" font-family="monospace" font-size="12" font-weight="bold">
    PREVIS CONTROL GUIDE • {shot_type} / {cam_angle} • [INTERNAL PLANNING ONLY]
  </text>

  <!-- Actors Staged as Previs Wireframe Silhouettes -->
"""
        for actor in staged.actors:
            cx = float(actor.x)
            top_y = float(actor.y)
            actor_h = float(actor.height)
            actor_w = max(actor_h * 0.35, 30.0)
            left_x = cx - (actor_w * 0.5)
            actor_id = getattr(actor, 'actor_id', 'actor')
            name = getattr(actor, 'name', 'Actor')
            svg += f"""  <g id="previs_{actor_id}">
    <rect x="{left_x:.1f}" y="{top_y:.1f}" width="{actor_w:.1f}" height="{actor_h:.1f}" rx="8" fill="#3f3f46" fill-opacity="0.4" stroke="#71717a" stroke-width="2" stroke-dasharray="4,4"/>
    <circle cx="{cx:.1f}" cy="{top_y + 24:.1f}" r="18" fill="#52525b" stroke="#a1a1aa" stroke-width="2"/>
    <text x="{cx:.1f}" y="{top_y + 28:.1f}" fill="#f4f4f5" font-family="sans-serif" font-size="11" text-anchor="middle" font-weight="bold">{html.escape(name[:12])}</text>
  </g>
"""
        # Lower metadata ribbon
        svg += f"""
  <rect x="0" y="{h - 36:.1f}" width="{w}" height="36" fill="#18181b" opacity="0.9"/>
  <text x="16" y="{h - 14:.1f}" fill="#a1a1aa" font-family="sans-serif" font-size="12">
    Shot {panel.shot_number}: {action_clean[:80]}
  </text>
  <rect width="{w}" height="{h}" fill="none" stroke="#52525b" stroke-width="2"/>
</svg>"""
        return svg
