"""Tests for Phase 6: Character Arcs + Subtext + Performance Cues.

Verifies:
1. Disillusionment arc detected for Arjun in The Missing Dossier.
2. Positive change arc detected when trust/goals improve.
3. Fall arc detected when morality degrades and goals fail.
4. Flat testing arc detected when beliefs survive pressure.
5. NO_ARC_DETECTED when delta_magnitude <= 0.25, with reason.
6. Transient emotion spike does NOT register as a turning point.
7. Turning point evidence event IDs are real simulation events.
8. Subjective false belief: character believing P=False says "P is false" -> TRUTHFUL, not LYING.
9. Maya dossier denial classified as LYING with private truth referenced.
10. Arjun does NOT receive Maya's private knowledge during analysis.
11. Evasive dialogue correctly classified.
12. Threatening dialogue correctly classified.
13. Manipulative dialogue correctly classified.
14. Vulnerable dialogue correctly classified.
15. Lying produces EYE_MOVEMENT or MICRO_EXPRESSION, showing not telling.
16. Threatening produces VOICE_CRACK or POSTURE_SHIFT.
17. Vulnerable produces BREATHING.
18. InternalStateVerbGuard rejects forbidden verbs.
19. All cues generated by PerformanceCueGenerator pass InternalStateVerbGuard.
20. Scene built by SceneBuilder can have character_arcs attached.
21. Scene built by SceneBuilder can have subtext_analyses attached.
22. Scene built by SceneBuilder can have performance_cues attached.
23. Full Phase 6 pipeline runs end-to-end on The Missing Dossier without errors.
"""

import pytest
from src.domain.world import WorldState, Location, WorldObject
from src.domain.character import Character, EmotionalState
from src.domain.goal import Goal, GoalStatus
from src.domain.relationship import Relationship
from src.domain.event import Event, EventType
from src.domain.proposition import Proposition, KnowledgeItem
from src.domain.story_structure import (
    ArcClassification,
    TurningPoint,
    CharacterArc,
    Scene,
    SceneObjective,
    DramaticFunction,
)
from src.narrative.arc_tracker import CharacterArcTracker
from src.narrative.subtext import (
    SubtextAnalyzer,
    DeceptionClassification,
    SubtextAnalysis,
)
from src.narrative.performance_cues import (
    PerformanceCueGenerator,
    PerformanceCueType,
    PerformanceCue,
    InternalStateVerbGuard,
)
from src.narrative.scene_builder import SceneBuilder
from src.narrative.observer import Observer
from src.narrative.causal_analyzer import CausalContinuityAnalyzer
from src.story.models import (
    StoryBlueprint,
    SufficiencyReport,
    PredicateSpec,
    PredicateClause,
)


# =============================================================================
# FIXTURES
# =============================================================================

@pytest.fixture
def dossier_world() -> WorldState:
    """Fixture providing a standard Hotel Room 307 / Missing Dossier world with typed knowledge."""
    world = WorldState(id="world_hotel_307", name="Hotel Room 307", current_tick=6)

    loc = Location(id="loc_room307", name="Hotel Room 307", connected_locations=[])
    world.locations[loc.id] = loc

    desk = WorldObject(id="obj_desk", name="Desk", location_id="loc_room307")
    dossier = WorldObject(id="obj_dossier", name="Classified Dossier", location_id="loc_room307")
    world.objects[desk.id] = desk
    world.objects[dossier.id] = dossier

    # Proposition: Dossier is inside the desk drawer
    prop = Proposition(
        id="prop_dossier_in_desk",
        subject="dossier",
        predicate="is_in",
        object="desk_drawer",
        truth_value=True,
    )
    world.propositions[prop.id] = prop

    # Arjun: Investigator who trusts Maya initially
    arjun = Character(
        id="char_arjun",
        name="Arjun",
        role="Corporate Investigator",
        current_location_id="loc_room307",
        emotional_state=EmotionalState(fear=0.2, anger=0.2, trust=0.6, curiosity=0.8),
    )
    # Maya: Attorney who knows the confidential location of the dossier
    maya = Character(
        id="char_maya",
        name="Maya",
        role="Corporate Attorney",
        current_location_id="loc_room307",
        emotional_state=EmotionalState(fear=0.5, anger=0.3, trust=-0.2, curiosity=0.4),
    )

    # Maya possesses the typed private knowledge item
    k_item = KnowledgeItem(
        proposition_id=prop.id,
        holder_id=maya.id,
        believed_truth_value=True,
        certainty=1.0,
        source="observed",
    )
    maya.knowledge[prop.id] = k_item

    world.characters[arjun.id] = arjun
    world.characters[maya.id] = maya

    # Initial relationship: Arjun trusts Maya (0.5)
    rel = Relationship(
        id="rel_arjun_maya",
        character_a_id="char_arjun",
        character_b_id="char_maya",
        affinity=0.4,
        trust=0.5,
    )
    world.relationships[rel.id] = rel
    arjun.relationships.append(rel.id)
    maya.relationships.append(rel.id)

    # Goal for Arjun
    g_arjun = Goal(
        id="goal_find_dossier",
        character_id="char_arjun",
        description="Find and verify the classified dossier",
        status=GoalStatus.ACTIVE,
    )
    world.goals[g_arjun.id] = g_arjun
    arjun.goals.append(g_arjun.id)

    return world


# =============================================================================
# 1. CHARACTER ARC TRACKER TESTS (1 - 7)
# =============================================================================

def test_01_disillusionment_arc_detected_for_arjun_in_missing_dossier(dossier_world):
    """1. Disillusionment arc detected for Arjun: trust drops > 0.4 from initial positive stance."""
    events = [
        Event(
            id="ev_01",
            tick=1,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=["char_arjun", "char_maya"],
            description="Arjun asks Maya about the missing dossier.",
        ),
        Event(
            id="ev_02",
            tick=2,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=["char_maya", "char_arjun"],
            description="Maya denies knowing anything about any dossier.",
            metadata={"dialogue": "I don't know anything about any dossier."},
        ),
        Event(
            id="ev_03",
            tick=3,
            event_type=EventType.OBJECT_PICKED_UP,
            actor_ids=["char_arjun"],
            description="Arjun discovers the concealed classified dossier in the desk drawer.",
        ),
        Event(
            id="ev_04",
            tick=4,
            event_type=EventType.RELATIONSHIP_CHANGED,
            actor_ids=["char_arjun", "char_maya"],
            description="Arjun confronts Maya on her betrayal; trust in Maya collapses completely.",
            metadata={"trust_delta": -0.8},
        ),
        Event(
            id="ev_05",
            tick=5,
            event_type=EventType.EMOTION_CHANGED,
            actor_ids=["char_arjun"],
            description="Arjun is disillusioned and embittered by the deceit.",
            metadata={
                "previous_emotional_state": {"fear": 0.2, "anger": 0.2, "trust": 0.6, "curiosity": 0.8},
                "emotional_state": {"fear": 0.3, "anger": 0.7, "trust": -0.5, "curiosity": 0.4},
            },
        ),
    ]
    for ev in events:
        dossier_world.events[ev.id] = ev

    # Final world state updates
    dossier_world.characters["char_arjun"].emotional_state = EmotionalState(fear=0.3, anger=0.7, trust=-0.5, curiosity=0.4)
    dossier_world.relationships["rel_arjun_maya"].trust = -0.5

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc("char_arjun", dossier_world, events)

    assert arc.character_id == "char_arjun"
    assert arc.classification == ArcClassification.DISILLUSIONMENT
    assert arc.starting_state["initial_emotions"]["trust"] >= 0.5
    assert arc.ending_state["final_emotions"]["trust"] <= -0.3
    assert len(arc.turning_points) > 0
    assert len(arc.evidence_event_ids) > 0
    assert "ev_04" in arc.evidence_event_ids or "ev_05" in arc.evidence_event_ids


def test_02_positive_change_arc_detected_when_trust_and_goals_improve():
    """2. Positive change arc detected when trust and goals improve."""
    world = WorldState(id="world_pos", name="Positive Arc World", current_tick=5)
    char = Character(
        id="char_elena",
        name="Elena",
        role="Operative",
        current_location_id="loc_base",
        emotional_state=EmotionalState(fear=0.7, anger=0.2, trust=-0.3, curiosity=0.5),
    )
    world.characters[char.id] = char

    goal = Goal(
        id="g_rescue",
        character_id=char.id,
        description="Rescue the hostages",
        status=GoalStatus.ACHIEVED,
        created_at_event="ev_g_achieved",
    )
    world.goals[goal.id] = goal
    char.goals.append(goal.id)

    rel = Relationship(
        id="rel_elena_allies",
        character_a_id=char.id,
        character_b_id="char_ally",
        trust=0.6,
        affinity=0.5,
    )
    world.relationships[rel.id] = rel

    ev1 = Event(
        id="ev_g_achieved",
        tick=4,
        event_type=EventType.BELIEF_FORMED,
        actor_ids=[char.id],
        description="Elena realizes the hostages are safe and trust is restored.",
    )
    world.events[ev1.id] = ev1

    # End state has improved emotions
    char.emotional_state = EmotionalState(fear=0.1, anger=0.1, trust=0.6, curiosity=0.6)

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc(char.id, world, [ev1])

    assert arc.classification == ArcClassification.POSITIVE_CHANGE
    assert len(arc.turning_points) > 0


def test_03_fall_arc_detected_when_morality_degrades_and_goals_fail():
    """3. Fall arc detected when morality degrades, anger/hostility mounts, and goals fail."""
    world = WorldState(id="world_fall", name="Fall Arc World", current_tick=5)
    char = Character(
        id="char_marcus",
        name="Marcus",
        role="Antagonist",
        current_location_id="loc_base",
        emotional_state=EmotionalState(fear=0.2, anger=0.85, trust=-0.8, curiosity=0.2),
    )
    world.characters[char.id] = char

    rel = Relationship(
        id="rel_marcus_world",
        character_a_id=char.id,
        character_b_id="char_rival",
        trust=-0.9,
        affinity=-0.8,
    )
    world.relationships[rel.id] = rel

    ev_fall = Event(
        id="ev_marcus_fall",
        tick=3,
        event_type=EventType.RELATIONSHIP_CHANGED,
        actor_ids=[char.id],
        description="Marcus succumbs to hostility and burns the bridge with all allies.",
    )
    world.events[ev_fall.id] = ev_fall

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc(char.id, world, [ev_fall])

    assert arc.classification == ArcClassification.FALL
    assert len(arc.turning_points) > 0


def test_04_flat_testing_arc_detected_when_beliefs_survive_pressure():
    """4. Flat testing arc detected when beliefs hold under pressure through major trials."""
    world = WorldState(id="world_flat", name="Flat Testing World", current_tick=5)
    char = Character(
        id="char_monk",
        name="Tenzin",
        role="Monk",
        current_location_id="loc_temple",
        emotional_state=EmotionalState(fear=0.1, anger=0.1, trust=0.1, curiosity=0.3),
    )
    world.characters[char.id] = char

    events = [
        Event(
            id="ev_test_1",
            tick=1,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=[char.id],
            description="Tenzin refuses to surrender the sacred text under torture.",
        ),
        Event(
            id="ev_test_2",
            tick=2,
            event_type=EventType.BELIEF_FORMED,
            actor_ids=[char.id],
            description="Tenzin's faith in the core doctrine is confirmed despite suffering.",
        ),
        Event(
            id="ev_test_3",
            tick=3,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=[char.id],
            description="Tenzin stands resolute before the inquisitor.",
        ),
    ]
    for e in events:
        world.events[e.id] = e

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc(char.id, world, events)

    assert arc.classification == ArcClassification.FLAT_TESTING
    assert len(arc.major_decisions) >= 2


def test_05_no_arc_detected_when_delta_magnitude_low_with_reason():
    """5. NO_ARC_DETECTED when no turning points with delta_magnitude > 0.25 detected, with reason."""
    world = WorldState(id="world_steady", name="Steady World", current_tick=4)
    char = Character(
        id="char_guard",
        name="Guard Davis",
        role="Security Guard",
        current_location_id="loc_gate",
        emotional_state=EmotionalState(fear=0.1, anger=0.1, trust=0.1, curiosity=0.1),
    )
    world.characters[char.id] = char

    events = [
        Event(
            id="ev_routine_1",
            tick=1,
            event_type=EventType.CHARACTER_MOVED,
            actor_ids=[char.id],
            description="Guard Davis patrols the quiet courtyard.",
        )
    ]
    for e in events:
        world.events[e.id] = e

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc(char.id, world, events)

    assert arc.classification == ArcClassification.NO_ARC_DETECTED
    assert arc.reason_if_none is not None
    assert len(arc.reason_if_none) > 0
    assert len(arc.turning_points) == 0


def test_06_transient_emotion_spike_does_not_register_as_turning_point():
    """6. Transient emotion spike that reverts to baseline does NOT register as a turning point."""
    world = WorldState(id="world_spike", name="Transient Spike World", current_tick=6)
    char = Character(
        id="char_sara",
        name="Sara",
        role="Scientist",
        current_location_id="loc_lab",
        emotional_state=EmotionalState(fear=0.2, anger=0.1, trust=0.2, curiosity=0.5),
    )
    world.characters[char.id] = char

    events = [
        # Baseline at tick 1
        Event(
            id="ev_base",
            tick=1,
            event_type=EventType.CHARACTER_MOVED,
            actor_ids=[char.id],
            description="Sara enters the laboratory.",
        ),
        # Transient spike at tick 2: fear spikes to 0.8
        Event(
            id="ev_spike",
            tick=2,
            event_type=EventType.EMOTION_CHANGED,
            actor_ids=[char.id],
            description="Sara jumps at a sudden loud crash in the shadows.",
            metadata={"emotional_state": {"fear": 0.8, "anger": 0.1, "trust": 0.2, "curiosity": 0.5}},
        ),
        # Reverts at tick 3: fear settles back to baseline 0.2
        Event(
            id="ev_revert",
            tick=3,
            event_type=EventType.EMOTION_CHANGED,
            actor_ids=[char.id],
            description="Sara chuckles realising it was just an empty beaker.",
            metadata={"emotional_state": {"fear": 0.2, "anger": 0.1, "trust": 0.2, "curiosity": 0.5}},
        ),
    ]
    for e in events:
        world.events[e.id] = e

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc(char.id, world, events)

    # The spike event "ev_spike" must NOT be registered as a persistent turning point
    tp_event_ids = [tp.event_id for tp in arc.turning_points]
    assert "ev_spike" not in tp_event_ids


def test_07_turning_point_evidence_event_ids_are_real_simulation_events(dossier_world):
    """7. Turning point evidence event IDs are verified real simulation events."""
    events = [
        Event(
            id="ev_real_01",
            tick=1,
            event_type=EventType.BELIEF_FORMED,
            actor_ids=["char_arjun"],
            description="Arjun confirms evidence of fraudulent activity.",
        ),
        Event(
            id="ev_real_02",
            tick=2,
            event_type=EventType.RELATIONSHIP_CHANGED,
            actor_ids=["char_arjun", "char_maya"],
            description="Arjun's trust collapses.",
        ),
    ]
    for e in events:
        dossier_world.events[e.id] = e

    tracker = CharacterArcTracker()
    arc = tracker.trace_arc("char_arjun", dossier_world, events)

    for eid in arc.evidence_event_ids:
        assert eid in dossier_world.events
    for tp in arc.turning_points:
        assert tp.event_id in dossier_world.events


# =============================================================================
# 2. SUBTEXT ANALYZER TESTS (8 - 14)
# =============================================================================

def test_08_subjective_false_belief_preservation():
    """8. Subjective false belief: character believing P=False says 'P is false' -> TRUTHFUL, NOT LYING."""
    world = WorldState(id="world_fb", name="False Belief World")
    prop = Proposition(
        id="prop_dossier_safe",
        subject="dossier",
        predicate="is_in",
        object="safe",
        truth_value=True,  # Canonically TRUE in objective reality
    )
    world.propositions[prop.id] = prop

    char = Character(
        id="char_bob",
        name="Bob",
        role="Analyst",
        current_location_id="loc_office",
        emotional_state=EmotionalState(fear=0.1, anger=0.1, trust=0.5, curiosity=0.3),
    )
    # Bob subjectively believes the proposition is FALSE
    char.knowledge[prop.id] = KnowledgeItem(
        proposition_id=prop.id,
        holder_id=char.id,
        believed_truth_value=False,
        certainty=0.9,
        source="inferred",
    )
    world.characters[char.id] = char

    analyzer = SubtextAnalyzer()
    # Bob says: "I don't have it, the dossier is not in the safe."
    analysis = analyzer.analyze(
        speaker=char,
        dialogue="I haven't seen any dossier in the safe.",
        world=world,
        listener_id="char_alice",
    )

    # Invariant: Because Bob subjectively believes it is False, asserting it is False is TRUTHFUL, not LYING
    assert analysis.spoken_intent == DeceptionClassification.TRUTHFUL
    assert analysis.primary_classification == DeceptionClassification.TRUTHFUL
    assert DeceptionClassification.LYING not in analysis.classifications


def test_09_maya_dossier_denial_classified_as_lying_with_private_truth_referenced(dossier_world):
    """9. Maya knows dossier is in desk drawer; denying it is LYING with private truth referenced."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="I don't know anything about any dossier.",
        world=dossier_world,
        listener_id="char_arjun",
        listener_ids=["char_arjun"],
    )

    assert analysis.spoken_intent == DeceptionClassification.LYING
    assert analysis.primary_classification == DeceptionClassification.LYING
    assert DeceptionClassification.LYING in analysis.classifications
    assert analysis.private_truth is not None
    assert "dossier" in analysis.private_truth.lower()
    assert analysis.cognitive_dissonance_score > 0.70


def test_10_arjun_does_not_receive_maya_private_knowledge_during_analysis(dossier_world):
    """10. Arjun must NOT receive Maya's private knowledge during or after subtext analysis."""
    arjun = dossier_world.characters["char_arjun"]
    maya = dossier_world.characters["char_maya"]
    target_prop_id = "prop_dossier_in_desk"

    # Verify Arjun does NOT possess this proposition before analysis
    assert target_prop_id not in arjun.knowledge

    analyzer = SubtextAnalyzer()
    analyzer.analyze(
        speaker=maya,
        dialogue="I haven't seen any dossier.",
        world=dossier_world,
        listener_id=arjun.id,
        listener_ids=[arjun.id],
    )

    # Verify Arjun STILL does NOT possess this proposition after analysis
    assert target_prop_id not in arjun.knowledge
    assert target_prop_id in maya.knowledge


def test_11_evasive_dialogue_correctly_classified(dossier_world):
    """11. Evasive dialogue correctly classified."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="Why do you ask? That's none of your business.",
        world=dossier_world,
        listener_id="char_arjun",
    )

    assert analysis.spoken_intent in (DeceptionClassification.EVASIVE, DeceptionClassification.DEFLECTING)
    assert any(c in analysis.classifications for c in (DeceptionClassification.EVASIVE, DeceptionClassification.DEFLECTING))


def test_12_threatening_dialogue_correctly_classified(dossier_world):
    """12. Threatening dialogue correctly classified."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="Step aside or else you'll regret this. I'm warning you.",
        world=dossier_world,
        listener_id="char_arjun",
    )

    assert analysis.spoken_intent == DeceptionClassification.THREATENING
    assert DeceptionClassification.THREATENING in analysis.classifications


def test_13_manipulative_dialogue_correctly_classified(dossier_world):
    """13. Manipulative dialogue correctly classified."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="Trust me, we're together in this. Think about what happens if you refuse.",
        world=dossier_world,
        listener_id="char_arjun",
    )

    assert analysis.spoken_intent == DeceptionClassification.MANIPULATIVE
    assert DeceptionClassification.MANIPULATIVE in analysis.classifications


def test_14_vulnerable_dialogue_correctly_classified(dossier_world):
    """14. Vulnerable dialogue correctly classified."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="I'm terrified. I can't do this anymore, please forgive me.",
        world=dossier_world,
        listener_id="char_arjun",
    )

    assert analysis.spoken_intent == DeceptionClassification.VULNERABLE
    assert DeceptionClassification.VULNERABLE in analysis.classifications


# =============================================================================
# 3. PERFORMANCE CUE GENERATOR TESTS (15 - 19)
# =============================================================================

def test_15_lying_produces_eye_movement_or_micro_expression_showing_not_telling(dossier_world):
    """15. Lying produces EYE_MOVEMENT or MICRO_EXPRESSION, showing not telling."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()
    generator = PerformanceCueGenerator()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="I haven't seen any dossier in this office.",
        world=dossier_world,
        listener_id="char_arjun",
    )
    cue = generator.generate_cue(
        analysis=analysis,
        character=maya,
        world=dossier_world,
        source_event_id="ev_speech_01",
    )

    assert cue.type in (PerformanceCueType.EYE_MOVEMENT, PerformanceCueType.MICRO_EXPRESSION)
    assert cue.character_id == maya.id
    assert cue.event_id == "ev_speech_01"
    # Action text shows physical behavior
    assert any(term in cue.observable_behaviour.lower() for term in ["gaze", "flicks", "jaw", "looks", "dossier"])
    assert InternalStateVerbGuard.validate_action_text(cue.observable_behaviour) is True


def test_16_threatening_produces_voice_crack_or_posture_shift(dossier_world):
    """16. Threatening produces VOICE_CRACK or POSTURE_SHIFT."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()
    generator = PerformanceCueGenerator()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="Leave now or you will face consequences.",
        world=dossier_world,
        listener_id="char_arjun",
    )
    cue = generator.generate_cue(
        analysis=analysis,
        character=maya,
        world=dossier_world,
        source_event_id="ev_threat_01",
    )

    assert cue.type in (PerformanceCueType.VOICE_CRACK, PerformanceCueType.POSTURE_SHIFT, PerformanceCueType.MICRO_EXPRESSION)
    assert InternalStateVerbGuard.validate_action_text(cue.observable_behaviour) is True


def test_17_vulnerable_produces_breathing(dossier_world):
    """17. Vulnerable produces BREATHING."""
    maya = dossier_world.characters["char_maya"]
    analyzer = SubtextAnalyzer()
    generator = PerformanceCueGenerator()

    analysis = analyzer.analyze(
        speaker=maya,
        dialogue="I'm scared. I can't do this anymore, please help me.",
        world=dossier_world,
        listener_id="char_arjun",
    )
    cue = generator.generate_cue(
        analysis=analysis,
        character=maya,
        world=dossier_world,
        source_event_id="ev_vuln_01",
    )

    assert cue.type == PerformanceCueType.BREATHING
    assert "breathing" in cue.observable_behaviour.lower() or "silence" in cue.observable_behaviour.lower()
    assert InternalStateVerbGuard.validate_action_text(cue.observable_behaviour) is True


def test_18_internal_state_verb_guard_rejects_forbidden_verbs():
    """18. InternalStateVerbGuard rejects forbidden internal verbs: knows, realizes, feels, remembers, is afraid, decides."""
    forbidden_samples = [
        "She knows he is lying.",
        "He realizes the trap is sprung.",
        "She feels afraid of the dark.",
        "He remembers the secret code.",
        "She is afraid to look at him.",
        "He decides to run for the exit.",
    ]
    for sample in forbidden_samples:
        assert InternalStateVerbGuard.validate_action_text(sample) is False
        with pytest.raises(ValueError, match="Action text violates 'Show, Don't Tell' rule"):
            InternalStateVerbGuard.check_and_raise(sample)

    valid_samples = [
        "Maya's gaze flicks toward the desk drawer.",
        "Arjun swallows hard before speaking.",
        "Maya's jaw tightens. A beat of calculated stillness.",
        "Arjun steps backward, widening the distance between them.",
    ]
    for sample in valid_samples:
        assert InternalStateVerbGuard.validate_action_text(sample) is True
        InternalStateVerbGuard.check_and_raise(sample)


def test_19_all_cues_generated_by_generator_pass_verb_guard(dossier_world):
    """19. All cues generated across all deception types pass InternalStateVerbGuard."""
    generator = PerformanceCueGenerator()
    speaker = dossier_world.characters["char_maya"]

    test_intents = [
        DeceptionClassification.TRUTHFUL,
        DeceptionClassification.EVASIVE,
        DeceptionClassification.CONCEALING,
        DeceptionClassification.HALF_TRUTH,
        DeceptionClassification.MISDIRECTING,
        DeceptionClassification.LYING,
        DeceptionClassification.MANIPULATIVE,
        DeceptionClassification.THREATENING,
        DeceptionClassification.DEFLECTING,
        DeceptionClassification.VULNERABLE,
    ]

    for intent in test_intents:
        mock_analysis = SubtextAnalysis(
            speaker_id=speaker.id,
            dialogue="Sample line for testing performance cue generation.",
            spoken_intent=intent,
            classifications=[intent],
            primary_classification=intent,
            underlying_motive="Test motive",
            conflict_focus_object="dossier",
        )
        cue = generator.generate_cue(
            analysis=mock_analysis,
            character=speaker,
            world=dossier_world,
            source_event_id=f"ev_test_{intent.value}",
        )
        assert InternalStateVerbGuard.validate_action_text(cue.observable_behaviour) is True
        assert InternalStateVerbGuard.validate_action_text(cue.action_text) is True


# =============================================================================
# 4. INTEGRATION TESTS (20 - 23)
# =============================================================================

def test_20_scene_can_have_character_arcs_attached(dossier_world):
    """20. Scene built by SceneBuilder can have character_arcs cleanly attached."""
    scene = Scene(
        scene_id="scene_01",
        scene_number=1,
        location_id="loc_room307",
        characters_present=["char_arjun", "char_maya"],
        source_event_ids=["ev_01"],
    )
    tracker = CharacterArcTracker()
    arc = tracker.trace_arc("char_arjun", dossier_world, [])

    scene.character_arcs["char_arjun"] = arc
    assert "char_arjun" in scene.character_arcs
    assert isinstance(scene.character_arcs["char_arjun"], CharacterArc)
    assert scene.character_arcs["char_arjun"].character_id == "char_arjun"


def test_21_scene_can_have_subtext_analyses_attached(dossier_world):
    """21. Scene built by SceneBuilder can have subtext_analyses cleanly attached."""
    scene = Scene(
        scene_id="scene_01",
        scene_number=1,
        location_id="loc_room307",
        characters_present=["char_arjun", "char_maya"],
        source_event_ids=["ev_01"],
    )
    analysis = SubtextAnalysis(
        speaker_id="char_maya",
        listener_ids=["char_arjun"],
        dialogue="I haven't seen it.",
        spoken_intent=DeceptionClassification.LYING,
        classifications=[DeceptionClassification.LYING],
        primary_classification=DeceptionClassification.LYING,
    )
    scene.subtext_analyses.append(analysis)
    assert len(scene.subtext_analyses) == 1
    assert scene.subtext_analyses[0].spoken_intent == DeceptionClassification.LYING


def test_22_scene_can_have_performance_cues_attached(dossier_world):
    """22. Scene built by SceneBuilder can have performance_cues cleanly attached."""
    scene = Scene(
        scene_id="scene_01",
        scene_number=1,
        location_id="loc_room307",
        characters_present=["char_arjun", "char_maya"],
        source_event_ids=["ev_01"],
    )
    cue = PerformanceCue(
        character_id="char_maya",
        type=PerformanceCueType.EYE_MOVEMENT,
        observable_behaviour="Maya's gaze flicks toward the desk drawer.",
        internal_trigger="Concealing dossier location",
        event_id="ev_01",
    )
    scene.performance_cues.append(cue)
    assert len(scene.performance_cues) == 1
    assert scene.performance_cues[0].type == PerformanceCueType.EYE_MOVEMENT
    assert "gaze flicks" in scene.performance_cues[0].observable_behaviour


def test_23_full_phase6_pipeline_runs_end_to_end_on_missing_dossier(dossier_world):
    """23. Full Phase 6 pipeline runs end-to-end on The Missing Dossier without errors:
    - Arjun arc: DISILLUSIONMENT
    - Maya subtext on denial: LYING
    - Performance cues for dialogue events
    - All cues pass InternalStateVerbGuard
    - Zero AI calls throughout.
    """
    # 1. Populate full canonical event log
    events = [
        Event(
            id="ev_101",
            tick=1,
            event_type=EventType.CHARACTER_MOVED,
            actor_ids=["char_arjun"],
            location_id="loc_room307",
            description="Arjun enters Hotel Room 307.",
        ),
        Event(
            id="ev_102",
            tick=2,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=["char_arjun", "char_maya"],
            location_id="loc_room307",
            description="Arjun asks Maya about the missing classified dossier.",
            metadata={"dialogue": "Where is the classified dossier, Maya?"},
        ),
        Event(
            id="ev_103",
            tick=3,
            event_type=EventType.CHARACTER_SPOKE,
            actor_ids=["char_maya", "char_arjun"],
            location_id="loc_room307",
            description="Maya denies knowing anything about any dossier.",
            metadata={"dialogue": "I don't know anything about any dossier."},
        ),
        Event(
            id="ev_104",
            tick=4,
            event_type=EventType.OBJECT_PICKED_UP,
            actor_ids=["char_arjun"],
            location_id="loc_room307",
            description="Arjun searches the desk drawer and retrieves the classified dossier.",
            metadata={"object_id": "obj_dossier"},
        ),
        Event(
            id="ev_105",
            tick=5,
            event_type=EventType.RELATIONSHIP_CHANGED,
            actor_ids=["char_arjun", "char_maya"],
            location_id="loc_room307",
            description="Arjun realizes Maya lied to him; his trust in her is completely shattered.",
            metadata={"trust_delta": -0.8},
        ),
        Event(
            id="ev_106",
            tick=6,
            event_type=EventType.EMOTION_CHANGED,
            actor_ids=["char_arjun"],
            location_id="loc_room307",
            description="Arjun's bitterness and disillusionment set in.",
            metadata={
                "previous_emotional_state": {"fear": 0.2, "anger": 0.2, "trust": 0.6, "curiosity": 0.8},
                "emotional_state": {"fear": 0.2, "anger": 0.7, "trust": -0.5, "curiosity": 0.3},
            },
        ),
    ]
    for ev in events:
        dossier_world.events[ev.id] = ev

    # Final world state updates
    dossier_world.characters["char_arjun"].emotional_state = EmotionalState(fear=0.2, anger=0.7, trust=-0.5, curiosity=0.3)
    dossier_world.relationships["rel_arjun_maya"].trust = -0.5

    # 2. Sufficiency Gate Report (PROCEED)
    sufficiency_report = SufficiencyReport(
        recommendation="PROCEED",
        score=85.0,
        required_beats_satisfied=True,
        climax_detected=True,
        arc_detected=True,
        satisfied_predicates=[],
        unsatisfied_predicates=[],
        reason="Dossier confrontation and retrieval executed satisfactorily.",
    )

    # 3. SceneBuilder builds scenes
    builder = SceneBuilder()
    scenes = builder.build_scenes(
        world=dossier_world,
        events=events,
        sufficiency_report=sufficiency_report,
    )
    assert len(scenes) >= 1

    # 4. Enrich scenes with Phase 6 structures
    enriched_scenes = builder.enrich_scenes_with_phase6(
        scenes=scenes,
        world=dossier_world,
        events=events,
    )
    assert len(enriched_scenes) >= 1
    main_scene = enriched_scenes[0]

    # Verify Character Arcs
    assert "char_arjun" in main_scene.character_arcs
    arjun_arc = main_scene.character_arcs["char_arjun"]
    assert arjun_arc.classification == ArcClassification.DISILLUSIONMENT
    assert len(arjun_arc.turning_points) > 0

    # Verify Subtext Analyses
    assert len(main_scene.subtext_analyses) >= 2
    # The denial line from Maya must be LYING
    maya_denial = next(
        (sub for sub in main_scene.subtext_analyses if sub.speaker_id == "char_maya"),
        None,
    )
    assert maya_denial is not None
    assert maya_denial.spoken_intent == DeceptionClassification.LYING
    assert maya_denial.private_truth is not None

    # Verify Performance Cues
    assert len(main_scene.performance_cues) >= 2
    for cue in main_scene.performance_cues:
        assert isinstance(cue, PerformanceCue)
        assert InternalStateVerbGuard.validate_action_text(cue.observable_behaviour) is True
        assert InternalStateVerbGuard.validate_action_text(cue.action_text) is True

    # 5. Verify Causal Continuity
    causal_analyzer = CausalContinuityAnalyzer()
    causal_report = causal_analyzer.analyze_causal_continuity(
        events=events,
        scenes=enriched_scenes,
        world=dossier_world,
    )
    assert causal_report is not None
